environment: production

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG

spring:
  datasource:
    url: jdbc:h2:mem:d2l-mockprod;DATABASE_TO_LOWER=TRUE;MODE=PostgreSQL
    driverClassName: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
