environment: development

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG

spring:
  datasource:
    url: jdbc:h2:mem:d2l-mockdev;DATABASE_TO_LOWER=TRUE;MODE=PostgreSQL
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true

  jpa:
    # generate-ddl: true
    show-sql: true
    hibernate.ddl-auto: create-drop
    defer-datasource-initialization: true
